###UTILISATEUR
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nom": "Larry Jossuca",
    "mail": "larryjossuc4@gmail.com",
    "password": "LarryJossuc4...",
    "quartier": 1
} 

###LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "profile": "Larry Jossuca",
    "password": "LarryJossuc4..."
}

###VERIFY TOKEN
POST http://localhost:3000/auth/verifyToken
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dGlsaXNhdGV1ciI6MiwibWFpbCI6ImxhcnJ5am9zc3VjNEBnbWFpbC5jb20iLCJpYXQiOjE3MjUyODAxNDd9.D7VrLWkvNx6nigcOdE5Ew9oaVaP6X4zfDEmjsEYGsls"
}

###Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dGlsaXNhdGV1ciI6MiwibWFpbCI6ImxhcnJ5am9zc3VjNEBnbWFpbC5jb20iLCJpYXQiOjE3MjUyODAxNDd9.D7VrLWkvNx6nigcOdE5Ew9oaVaP6X4zfDEmjsEYGsls

###GET ALL USERS
GET http://localhost:3000/user/all
Content-Type: application/json 

###PUBLISH COMMAND
POST http://localhost:3000/iot/publish
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dGlsaXNhdGV1ciI6MiwibWFpbCI6ImxhcnJ5am9zc3VjNEBnbWFpbC5jb20iLCJpYXQiOjE3MjUyODAxNDd9.D7VrLWkvNx6nigcOdE5Ew9oaVaP6X4zfDEmjsEYGsls

{
    "topic": "esp32/led",
    "payload": "{\"message\": \"ON\"}"
}

###SUBSCRIBE DATA  
POST http://localhost:3000/iot/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dGlsaXNhdGV1ciI6MiwibWFpbCI6ImxhcnJ5am9zc3VjNEBnbWFpbC5jb20iLCJpYXQiOjE3MjUyODAxNDd9.D7VrLWkvNx6nigcOdE5Ew9oaVaP6X4zfDEmjsEYGsls

{
    "topic": "esp32/led"
}

###Admin register
POST http://localhost:3000/admin/auth/register
Content-Type: application/json

{
    "nom": "Larry",
    "mail": "jossuc4@gmail.com",
    "password": "admin"
}

####Admin login
POST http://localhost:3000/admin/auth/login
Content-Type: application/json

{
    "profile": "jossuc4@gmail.com",
    "password": "admin"
}

####Admin logout
POST http://localhost:3000/admin/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dGlsaXNhdGV1ciI6MSwibWFpbCI6Impvc3N1YzRAZ21haWwuY29tIiwiaWF0IjoxNzI1NDM1NzE2fQ.ItHKrjSEIenJCRKCQD0AqyJJBvzwU0eio9WysijgwPI


###Subscribe data
GET http://localhost:3000/iot/subscribe